//
//  GetNewWeatherItemWorker.swift
//  OpenWeatherMap
//
//  Created by msm72 on 21.04.16.
//  Copyright (c) 2016 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Alamofire

class GetNewWeatherItemWorker {

    let keyAPI = "bf78c70c3c7cc215ec6f26b3437a2409"
    var urlAPI = "http://api.openweathermap.org/data/2.5/forecast/daily?q=London,uk&lang=ua&appid="

    // MARK: - GET API -
    func doSomeWork() {
        // NOTE: - Alamofire -
        urlAPI += keyAPI
        
        Alamofire.request(.GET, urlAPI).responseJSON() {
            (JSON) in
            print(JSON)
        }
    }
}
