//
//  WeatherListInteractor.swift
//  OpenWeatherMap
//
//  Created by msm72 on 21.04.16.
//  Copyright (c) 2016 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol WeatherListInteractorInput {
    func doSomething(request: WeatherListRequest)
}

protocol WeatherListInteractorOutput {
    func presentSomething(response: WeatherListResponse)
}

class WeatherListInteractor: WeatherListInteractorInput {
    var output: WeatherListInteractorOutput!
    var workerGetNewWeatherItem: GetNewWeatherItemWorker!
  
    // MARK: - Business logic -
    func doSomething(request: WeatherListRequest) {
        // NOTE: Create some Worker to do the work
        workerGetNewWeatherItem = GetNewWeatherItemWorker()
        workerGetNewWeatherItem.doSomeWork()
    
        // NOTE: Pass the result to the Presenter
        let response = WeatherListResponse()
        output.presentSomething(response)
  }
}
