//
//  WeatherListModels.swift
//  OpenWeatherMap
//
//  Created by msm72 on 21.04.16.
//  Copyright (c) 2016 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// NOTE: - View Controller Request Model -
struct WeatherListRequest {
}


// NOTE: - Interactor Response Model -
struct WeatherListResponse {
}


// NOTE: - Presenter View Model -
struct WeatherListViewModel {
}
